name: Release Please - Apps

on:
  push:
    branches:
      - staging

jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-latest
    steps:
      - name: Run Release Please Action
        uses: googleapis/release-please-action@v4
        with:
          target-branch: staging
          config-file: "release-please-apps-config.json"
          manifest-file: ".release-please-apps-manifest.json"
          token: ${{ secrets.GITHUB_TOKEN }}