name: Release Please - Packages

on:
  push:
    branches:
      - development

jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-latest
    steps:
      - name: Run Release Please Action
        uses: googleapis/release-please-action@v4
<<<<<<< HEAD:.github/workflows/release-please-apps.yml
        with:
          labels: "autorelease: pending"
=======
>>>>>>> 71e347f3eec8eab3c58d7a4a5ba6267b475672aa:.github/workflows/release-please.yml
