name: Release Please - Packages

on:
  push:
    branches:
      - development

jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-latest
    steps:
      - name: Run Release Please Action
        uses: googleapis/release-please-action@v4
        with:
          target-branch: development
          config-file: "release-please-packages-config.json"
          manifest-file: ".release-please-packages-manifest.json"
